# SPDX-FileCopyrightText: Timothée Ravier <tim@siosm.fr>
# SPDX-License-Identifier: CC0-1.0

ARG RELEASE=overridden
FROM registry.fedoraproject.org/fedora-minimal:${RELEASE}
RUN --mount=type=tmpfs,target=/run \
    --mount=type=tmpfs,target=/tmp \
    --mount=type=tmpfs,target=/var \
set -euxo pipefail; \
rm -f "/etc/yum.repos.d/fedora-cisco-openh264.repo"; \
dnf install -y systemd-ukify sbsigntools jq; \
dnf install -y --enablerepo=updates-testing --refresh bootc; \
mkdir -p /boot/EFI/Linux
