# SPDX-FileCopyrightText: Timothée Ravier <tim@siosm.fr>
# SPDX-License-Identifier: CC0-1.0

ARG RELEASE=overridden
FROM registry.fedoraproject.org/fedora-minimal:${RELEASE} as builder

RUN \
set -euxo pipefail; \
rm -f "/etc/yum.repos.d/fedora-cisco-openh264.repo"; \
dnf install -y systemd-boot-unsigned sbsigntools

RUN --mount=type=tmpfs,target=/run \
    --mount=type=secret,id=secureboot_key \
    --mount=type=secret,id=secureboot_crt \
set -euxo pipefail; \
sbsign \
    --key /run/secrets/secureboot_key \
    --cert /run/secrets/secureboot_crt \
    --output /systemd-bootx64.efi \
    /usr/lib/systemd/boot/efi/systemd-bootx64.efi

FROM scratch
COPY --from=builder /systemd-bootx64.efi /systemd-bootx64.efi
