on:
  push:
    branches:
    - main
  workflow_dispatch:
permissions:
  packages: write
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - uses: redhat-actions/podman-login@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: build
      env:
        SIGSTORE_PRIVATE: ${{ secrets.SIGSTORE_PRIVATE }}
        DB_KEY: ${{ secrets.DB_KEY }}
      run: |
        set -euxo pipefail

        eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
        which just || brew install just

        just gh-setup
        tree -h ~/.config/containers
        cat ~/.config/containers/policy.json
        cat ~/.config/containers/registries.d/sigstore.yaml 
        # just PROJECT_REPO="ghcr.io/${GITHUB_REPOSITORY%/*}" build-seal-push

        # git push
