on:
  schedule:
  - cron: '0 4 * * *'
  workflow_dispatch:
permissions:
  packages: write
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: ublue-os/remove-unwanted-software@v9
    - uses: actions/checkout@v6
    - uses: redhat-actions/podman-install@main
    - uses: redhat-actions/podman-login@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: build
      env:
        SIGSTORE_PRIVATE: ${{ secrets.SIGSTORE_PRIVATE }}
        DB_KEY: ${{ secrets.DB_KEY }}
      run: |
        set -euxo pipefail

        eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
        which just || brew install just

        just PROJECT_REPO="ghcr.io/${GITHUB_REPOSITORY%/*}" gh-setup
        just PROJECT_REPO="ghcr.io/${GITHUB_REPOSITORY%/*}" update

        git push
